//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Departman
    {
        public Departman()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int Id { get; set; }

        [Display(Name="Departman Adý")]
        [Required(ErrorMessage="Departman Adý Zorunludur...")]
        public string Ad { get; set; }
    
        public virtual ICollection<Personel> Personel { get; set; }
    }
}
